name: OCI ARM Auto Provision

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  run-oci-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Create Private Key File
        run: |
          cat << 'EOF' > key.pem
          -----BEGIN PRIVATE KEY-----
          MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDh+qUZUOx+ATbL
          UKbEaMPSNUct3685Ca+wxdzs+Kv30WFU9QokkluJzYD533ULEmxn/5JEovQmOjxM
          wPgMkbV0RXG1Ok58bHjL3yDg0AKmhwCHO4L7b6uNpn8mmGRWYimPRGJRneZxJlLM
          9ZoKkV4XuApxbYTuU+GEC0nmcd8fbz7DKygAMQh8v+VTHWmsLvlFztsiK3X5JBQ+
          Ks2325hpAmPTeStlHpnTwXXWvNtNd02WdMikGozKi+T8e5BIwSDuK3aadUwpWX5Z
          1PXmRN3uuGmcdcbISoWVFLLRKGW+Cum3MGqiycPfKgLKV9+CJNbw83XQvdEo7OXe
          o1fW0FbHAgMBAAECggEAB1dOH7lqRVmivw4arMy+d8i1TD81AQRYicSTvbsCUyWh
          JNJlBvUeNibP5s4kjjyF+wbpaINmrQs9RD0MkdP18hYDcKC5Rf98GRthhQwc2e4O
          zVXYlnR1PT/IZ6eRsuCzeuz8yKv5fXmCPRhJbch1Jw4agL7PD7L344M+XlcaqXmz
          DazV2yAdrywCV+N1RasTRIrdX9a2oDBpqyU0pzXbFKo6203D/ce3bJHOJh4deqcB
          HPkUl7PTs2iRdFKM46AM8Ysx7SnnzB/myNXu4POlgYABq8X99MXOsW74gwNhHaU8
          eXCgZ1ecUneDYqDpcQIcd3p/6CEFV8Ky7+reVAq0wQKBgQD2DBqwvS5Dy52t/+Mc
          Tnous41HUv1OOg9zaN9NuRasNKWRxBzNOeV6N6EWnyXat0KdQNEqoh5zQn/LvCsz
          s4hXGCIl1xn0ORjR99tnc1uOcdDsk17wTVxXyWRQYAQBtrwmA6v+oByjCOTtWgze
          SSlDirNzYLz53IfojB4qf6yT5wKBgQDrHrptaAymt2xYSMpV42BEbLlZxFkGz6tu
          gQTSEm2XIRYN4KGX0gl7cSvzAbBNVJ1UWbRDXqSDcDTgv+R6JFHZ4Jnpq7BcYkfH
          WVnoC3ArZaKwKm/4qGlAw+neLNtER/TtdwW0Cl7E9gi9KY27XssPa6pCVPUAFmZZ
          PC2cGJvKIQKBgBKwZK6cEBGSO83lq+iQhXNarBaI1TjF7DqF8sBCmNhHv3PNA6sL
          BMU9yHyhZgyw8txi+gBVBB8ZI//jsRxiPK7w5FcfeZc1Zw871myLNJ8jQg1WPFXg
          am04nOgGAwfmS3BPwxa6LrKrkEf/GQ8hW4MH3A2dgX0xJRmi2v+7Zu5tAoGAeBvn
          cpJvvA8BiwwMSNnxyKKeAQx7yi32TmocU1BUqZqeUJKLGiqS63uBzw7yyF5MTNXS
          b4P+mKKOcK22gurg4WOKXMN3QYp3TpAHjLGjKJgwBrx3HNizhAFRDE1v6a60oUZn
          JHUTupxRFIkQvUIMi6EdhesuiU/oEvfZ+N7dXuECgYEAwNcMhWxOqwiyVfrSzFxu
          Uo5icpeQRDxwe18DkmwpT3rc2wMfImBitYJKcTKKdxrS5+TelCt60y9Ka2P/8JMB
          ubQybmCJ/OQZAu19bRE/SEgTJ3udd8MkErrQ8/CbmpC7xBpyTvPAjQuEVDGsKJYW
          r0Sr0lPvNtAe153lTqAIMlw=
          -----END PRIVATE KEY-----
          EOF
          chmod 600 key.pem

      - name: Create .env File
        run: |
          cat << 'EOF' > .env
          OCI_USER_ID=ocid1.user.oc1..aaaaaaaadqa3itsoc3cxwyyjk4mos4o5tqtegm7j7xktzl2vhiqslotqamia
          OCI_TENANCY_ID=ocid1.tenancy.oc1..aaaaaaaabfzjfg2dytvepao73ruuheb2edpn3jpfuju4ryqavhgcb7v5a7nq
          OCI_REGION=ap-batam-1
          OCI_KEY_FINGERPRINT=fc:a1:6e:a9:19:65:9f:cb:57:c2:d0:0d:ad:a2:ae:f7
          OCI_SUBNET_ID=ocid1.subnet.oc1.ap-batam-1.aaaaaaaaje3hbjvqob443z3jipfwttggshiglblxv2fdmos7jygyzdoq4y6q
          OCI_PRIVATE_KEY_FILENAME=key.pem
          OCI_SHAPE=VM.Standard.A1.Flex
          OCI_OCPUS=2
          OCI_MEMORY=6
          OCI_AVAILABILITY_DOMAIN=
          OCI_IMAGE_ID=
          OCI_SSH_PUBLIC_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDhDyH1X1N/QTy02qVRWdBGnyxEHKeZ9z+aj2unmXH71d716u621M01QJw0W/rv28NKbP86gbHpSLDrjM/aAukaaxbGgovVwGRxmOgr8fK8mYfNhJn1kkrRhdUL4AZ37CiVig08A8q+V7i2k9EW5W9+5augm3S3C101Yfs32/muPMjoKON15rAXnLe6chKfajPcBXJ3wfQhgX3GrWh/5jB0VM4wfPQnS6fZKKERDZEB51TeUbvpnzoTh+3MKXUk+xD13b16A0Q/zLSNdDxBAywTYQEFN0qXBsW6fCUNiiakOhYOeD1yDP7g3dH+B8P2/TzekqFY94tT home@IQBAL
          EOF

      - name: Install dependencies
        run: composer install

      - name: Execute OCI Auto Instance Script
        run: php index.php
